services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pricecomparison
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  main:
    container_name: pricecomparison
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env_product
    depends_on:
      - mysql
    networks:
      - mynetwork

  crawler:
    container_name: price_hawk_crawler
    build:
      context: .
      dockerfile: price-hawk/docker/Dockerfile.cron
    volumes:
      - ./price-hawk/logs:/app/price-hawk/logs
    env_file:
      - ./price-hawk/.env_product
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork: