name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          command_timeout: 30m
          script: |
            cd /root/pricehawk/PriceHawk_S4
            git fetch origin
            git reset --hard origin/main

            # Tạo file .env.product từ GitHub Secret
            echo "${{ secrets.ENV_PRODUCT }}" > .env.product
            echo "${{ secrets.ENV_CHATBOT }}" > ./chatbot/.env.product
            echo "${{ secrets.ENV_CRAWLER }}" > ./price-hawk/.env.product

            docker compose up -d --build --remove-orphans